

services:

#setting up mysql db 
  mysqltest:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password123#
      MYSQL_DATABASE: mysqltest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data1:/var/lib/mysql


#setting up phpmyadmin UI
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysqltest 
    restart: always
    ports:
      - 8081:80
#Adding env var PMA_HOST to see if it solves the problem of phymyadmin not seeing the mysql server.
#It solves the problem but only after setting the value to "mysqltest" which is the name of the database instance created inside mysql.
#I initially set PMA_HOST: localhost and this didn't work. I did this because on the official documentation of phpmyadmin docker page, it states "PMA_HOST - define address/host name of the MySQL server"


volumes:
  mysql-data1:
    driver: local
