

services:

#setting up mysql db 
  mysqltest:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123#
      MYSQL_DATABASE: mysqltest

#setting up phpmyadmin UI
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=localhost

volumes:
  mysql-data:
    driver: local
